### ISSUE TITLE
ruby 2.3.0 gona make me mad

### ISSUE THREAD

**Issue by nemgun21** [devrandom/gitian-builder#124]
here it is clearly:

nemgun@ubuntu:~/gitian-builder$ sudo bin/gbuild ..blumedtoken/contrib/gitian-descriptors/deps-win32.yml
/usr/lib/ruby/2.3.0/psych.rb:471:in `initialize': No such file or directory @ rb_sysopen - ..blumedtoken/contrib/gitian-descriptors/deps-win32.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:471:in `load_file'
	from bin/gbuild:201:in `<main>'

**Comment by nemgun21** [comment]
i think i the problem is with psych.rb
i tried building linux wallets but it is the same error, again, and again.

**Comment by nemgun21** [comment]
ok, i got it, wrong path to the yml. GUYS NEVER FORGET " / "
nemgun@ubuntu:~/gitian-builder$ sudo bin/gbuild ..**/**blumedtoken/contrib/gitian-descriptors/deps-win32.yml
