### ISSUE TITLE
Failed to load rcfile

### ISSUE THREAD

**Issue by josephnicholas** [devrandom/gitian-builder#190]
Good day @devrandom .

I have this issue whenever I do a build, this happens on both `--kvm` and `lxc`.

Still new to this gitian builder but I can't continue on the error, and I already researched alot and no one seems to be having this error. Please help.

* OS: Ubuntu 18.04
* Suite: Trusty
```
Failed to load rcfile
Traceback (most recent call last):
	6: from ./bin/gbuild:301:in `<main>'
	5: from ./bin/gbuild:301:in `each'
	4: from ./bin/gbuild:303:in `block in <main>'
	3: from ./bin/gbuild:303:in `each'
	2: from ./bin/gbuild:308:in `block (2 levels) in <main>'
	1: from ./bin/gbuild:57:in `build_one_configuration'
./bin/gbuild:21:in `system!': failed to run make-clean-vm --suite trusty --arch amd64 (RuntimeError)
Traceback (most recent call last):
./bin/gsign:70:in `<main>': result/zcoin-linux-0.13.6-res.yml does not exist (RuntimeError)
Traceback (most recent call last):
	3: from ./bin/gbuild:215:in `<main>'
	2: from /usr/lib/ruby/2.5.0/psych.rb:497:in `load_file'
	1: from /usr/lib/ruby/2.5.0/psych.rb:497:in `open'
/usr/lib/ruby/2.5.0/psych.rb:497:in `initialize': No such file or directory @ rb_sysopen - ../zcoin/contrib/gitian-descriptors/gitian-win-utils.yml (Errno::ENOENT)
```

**Comment by achow101** [comment]
You should not see this error with `kvm` because it does not use something called an rcfile.

With lxc, you will see this error if you are using lxc 3. #178 will fix this.

**Comment by josephnicholas** [comment]
@achow101 and @devrandom Thanks
