### ISSUE TITLE
Problems with proxy on docker on Fedora 30

### ISSUE THREAD

**Issue by soeren-b-c** [devrandom/gitian-builder#227]
I have a clean Fedora 30 netinstall 

When running
`bin/make-base-vm --docker --arch amd64`
I see this
`Step 3/8 : RUN echo 'Acquire::http { Proxy "http://172.17.0.1:3142"; };' > /etc/apt/apt.conf.d/50cacher`
followed by the error
`E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Unable to connect to 172.17.0.1:3142:`

I have a feeling it may as well be a docker problem, but I can't figure out where to go from here.

I get similar errors about failing to fetch from the proxy when trying to run with `--dist debian` or other `--suite`.

Full output:
```
$ bin/make-base-vm --docker --arch amd64
Sending build context to Docker daemon 4.096 kB
Step 1/8 : FROM ubuntu:xenial
Trying to pull repository docker.io/library/ubuntu ... 
sha256:e9938f45e51d9ff46e2b05a62e0546d0f07489b7f22fbc5288defe760599e38a: Pulling from docker.io/library/ubuntu
Digest: sha256:e9938f45e51d9ff46e2b05a62e0546d0f07489b7f22fbc5288defe760599e38a
Status: Image is up to date for docker.io/ubuntu:xenial
 ---> 77be327e4b63
Step 2/8 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 5900fc91e2a4
Step 3/8 : RUN echo 'Acquire::http { Proxy "http://172.17.0.1:3142"; };' > /etc/apt/apt.conf.d/50cacher
 ---> Using cache
 ---> 4a19f86c4496
Step 4/8 : RUN apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release linux-image-generic grub-pc openssh-server
 ---> Running in 5313e0d3d48b
Ign:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign:2 http://security.ubuntu.com/ubuntu xenial-security Release
Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
Ign:4 http://archive.ubuntu.com/ubuntu xenial InRelease
Ign:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Ign:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Ign:14 http://archive.ubuntu.com/ubuntu xenial Release
Ign:15 http://archive.ubuntu.com/ubuntu xenial-updates Release
Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:16 http://archive.ubuntu.com/ubuntu xenial-backports Release
Ign:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Ign:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Ign:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Err:3 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
  Unable to connect to 172.17.0.1:3142:
Ign:7 http://security.ubuntu.com/ubuntu xenial-security/main all Packages
Ign:8 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Ign:9 http://security.ubuntu.com/ubuntu xenial-security/restricted all Packages
Ign:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
Ign:11 http://security.ubuntu.com/ubuntu xenial-security/universe all Packages
Ign:12 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
Ign:13 http://security.ubuntu.com/ubuntu xenial-security/multiverse all Packages
Ign:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Ign:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Ign:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Ign:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Ign:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Err:17 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages
  Unable to connect to 172.17.0.1:3142:
Ign:18 http://archive.ubuntu.com/ubuntu xenial/main all Packages
Ign:19 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
Ign:20 http://archive.ubuntu.com/ubuntu xenial/restricted all Packages
Ign:21 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
Ign:22 http://archive.ubuntu.com/ubuntu xenial/universe all Packages
Ign:23 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
Ign:24 http://archive.ubuntu.com/ubuntu xenial/multiverse all Packages
Err:25 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
  Unable to connect to 172.17.0.1:3142:
Ign:26 http://archive.ubuntu.com/ubuntu xenial-updates/main all Packages
Ign:27 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
Ign:28 http://archive.ubuntu.com/ubuntu xenial-updates/restricted all Packages
Ign:29 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
Ign:30 http://archive.ubuntu.com/ubuntu xenial-updates/universe all Packages
Ign:31 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
Ign:32 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse all Packages
Err:33 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
  Unable to connect to 172.17.0.1:3142:
Ign:34 http://archive.ubuntu.com/ubuntu xenial-backports/main all Packages
Ign:35 http://archive.ubuntu.com/ubuntu xenial-backports/restricted amd64 Packages
Ign:36 http://archive.ubuntu.com/ubuntu xenial-backports/restricted all Packages
Ign:37 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
Ign:38 http://archive.ubuntu.com/ubuntu xenial-backports/universe all Packages
Ign:39 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse amd64 Packages
Ign:40 http://archive.ubuntu.com/ubuntu xenial-backports/multiverse all Packages
Reading package lists...
W: The repository 'http://security.ubuntu.com/ubuntu xenial-security Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu xenial-backports Release' does not have a Release file.
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Unable to connect to 172.17.0.1:3142:
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/main/binary-amd64/Packages  Unable to connect to 172.17.0.1:3142:
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages  Unable to connect to 172.17.0.1:3142:
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Unable to connect to 172.17.0.1:3142:
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release linux-image-generic grub-pc openssh-server' returned a non-zero code: 100
```

**Comment by MarkLTZ** [comment]
Hello! I have the same issue. Did you solve it?

**Comment by soeren-b-c** [comment]
@MarkLTZ No, unfortunately I did not.

I still suspect that there is something going on with the docker networking / proxy, but I have never used docker before, so I am kinda flying blind here... :(

If you have a breakthrough, please let me know.

**Comment by MarkLTZ** [comment]
ok. for the moment I have configured it using ubuntu on Virtual Box

**Comment by abitmore** [comment]
See https://github.com/devrandom/gitian-builder/issues/228#issuecomment-643518340.

**Comment by soeren-b-c** [comment]
@abitmore Thanks for replying. How do you run that command on Fedora? I don't think apt-cacher-ng is included in the latest Fedora.

**Comment by abitmore** [comment]
If I'm correct, Fedora doesn't have `apt`, so there will be no `apt-cacher-ng` service on the host. I guess you need to remove the proxy settings from the code, see https://github.com/devrandom/gitian-builder/issues/66#issuecomment-53166671 and https://github.com/devrandom/gitian-builder/issues/66#issuecomment-53523363.

**Comment by devrandom** [comment]
Could also run apt-cacher-ng in a docker container - maybe https://github.com/deployable/docker-apt-cacher-ng .  But I haven't tried it myself.

Pull requests to improve docs and/or disable caching would be appreciated.

**Comment by fhivemind** [comment]
I was experiencing the same issue and managed to resolve it by restarting the apt-cacher service. 

```service apt-cacher-ng restart```

**Comment by losh11** [comment]
@devrandom I'm experiencing the same output as OP when trying to setup using the gitian script with docker on Ubuntu 20.04.

```
losh11@Loshans-PC:~/Repos$ ./gitian-build.py --setup --docker losh11 0.18.1
Cannot build for MacOS, SDK does not exist. Will build for other OSes
Cloning into 'gitian.sigs'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 806 bytes | 806.00 KiB/s, done.
Cloning into 'bitcoin-detached-sigs'...
remote: Enumerating objects: 279, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 279 (delta 4), reused 24 (delta 4), pack-reused 255
Receiving objects: 100% (279/279), 5.30 MiB | 7.15 MiB/s, done.
Resolving deltas: 100% (48/48), done.
Cloning into 'gitian-builder'...
remote: Enumerating objects: 1330, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 1330 (delta 32), reused 46 (delta 18), pack-reused 1265
Receiving objects: 100% (1330/1330), 331.38 KiB | 1.38 MiB/s, done.
Resolving deltas: 100% (727/727), done.
Cloning into 'bitcoin'...
remote: Enumerating objects: 121321, done.
remote: Total 121321 (delta 0), reused 0 (delta 0), pack-reused 121321
Receiving objects: 100% (121321/121321), 111.47 MiB | 6.03 MiB/s, done.
Resolving deltas: 100% (82879/82879), done.
Generating public/private rsa key pair.
Your identification has been saved in var/id_rsa
Your public key has been saved in var/id_rsa.pub
The key fingerprint is:
SHA256:RI/85hwrzn1MlQfZSJQJhFgdbBFlzByW2RXJ0EOr+94 losh11@Loshans-PC
The key's randomart image is:
+---[RSA 3072]----+
|        .o.=*&%&=|
|       o.o. +o%=+|
|        + ..   +.|
|       . .    + .|
|        S +  o . |
|         + o. .  |
|        . +o .   |
|       o o  o . .|
|        o ..  .oE|
+----[SHA256]-----+
[+] Building 12.3s (6/8)
 => [internal] load build definition from base-bionic-amd64.Dockerfile                                                                                                                                                                        0.0s
 => => transferring dockerfile: 502B                                                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:bionic                                                                                                                                                                             12.0s
 => [1/5] FROM docker.io/library/ubuntu:bionic@sha256:9bc830af2bef73276515a29aa896eedfa7bdf4bdbc5c1063b4c457a4bbb8cd79                                                                                                                        0.0s
 => CACHED [2/5] RUN echo 'Acquire::http { Proxy "http://172.17.0.1:3142"; };' > /etc/apt/apt.conf.d/50cacher                                                                                                                                 0.0s
 => ERROR [3/5] RUN apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release sudo linux-image-generic grub-pc openssh-server                                    0.3s
------
 > [3/5] RUN apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release sudo linux-image-generic grub-pc openssh-server:
#5 0.214 Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
#5 0.214   Could not connect to 172.17.0.1:3142 (172.17.0.1). - connect (111: Connection refused)
#5 0.214 Err:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
#5 0.214   Unable to connect to 172.17.0.1:3142:
#5 0.214 Err:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
#5 0.214   Unable to connect to 172.17.0.1:3142:
#5 0.214 Err:4 http://security.ubuntu.com/ubuntu bionic-security InRelease
#5 0.214   Could not connect to 172.17.0.1:3142 (172.17.0.1). - connect (111: Connection refused)
#5 0.215 Reading package lists...
#5 0.219 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Could not connect to 172.17.0.1:3142 (172.17.0.1). - connect (111: Connection refused)
#5 0.219 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Unable to connect to 172.17.0.1:3142:
#5 0.219 W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Unable to connect to 172.17.0.1:3142:
#5 0.219 W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Could not connect to 172.17.0.1:3142 (172.17.0.1). - connect (111: Connection refused)
#5 0.219 W: Some index files failed to download. They have been ignored, or old ones used instead.
#5 0.221 Reading package lists...
#5 0.225 Building dependency tree...
#5 0.225 Reading state information...
#5 0.226 E: Unable to locate package pciutils
#5 0.226 E: Unable to locate package build-essential
#5 0.226 E: Unable to locate package git
#5 0.226 E: Unable to locate package subversion
#5 0.226 E: Unable to locate package language-pack-en
#5 0.226 E: Unable to locate package wget
#5 0.226 E: Unable to locate package lsb-release
#5 0.226 E: Unable to locate package sudo
#5 0.226 E: Unable to locate package linux-image-generic
#5 0.226 E: Unable to locate package grub-pc
#5 0.226 E: Unable to locate package openssh-server
------
executor failed running [/bin/sh -c apt-get update && apt-get --no-install-recommends -y install pciutils build-essential git subversion language-pack-en wget lsb-release sudo linux-image-generic grub-pc openssh-server]: exit code: 100
Traceback (most recent call last):
  File "./gitian-build.py", line 233, in <module>
    main()
  File "./gitian-build.py", line 209, in main
    setup()
  File "./gitian-build.py", line 39, in setup
    subprocess.check_call(make_image_prog)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bin/make-base-vm', '--suite', 'bionic', '--arch', 'amd64', '--docker']' returned non-zero exit status 1.
```

Does this mean I shouldn't be using the gitian script to setup?

**Comment by devrandom** [comment]
It is a known issue that Gitian depends on an apt-cache mirror.  You can set it to some host other than the default via the MIRROR_HOST environment variable.

The PR https://github.com/devrandom/gitian-builder/pull/249 seems promising, but I'm still waiting for the author to make the modification I requested.
