### ISSUE TITLE
ERROR: umount: /tmp/tmpXXXXX/dev: device is busy

### ISSUE THREAD

**Issue by piotrnar** [devrandom/gitian-builder#25]
This is what I get with the latest version (Ubuntu 12)

> bin/make-base-vm -arch i386
2012-09-12 11:36:23,989 INFO    : Calling hook: preflight_check
2012-09-12 11:36:23,991 INFO    : Calling hook: set_defaults
2012-09-12 11:36:23,992 INFO    : Calling hook: bootstrap
2012-09-12 11:37:22,330 INFO    : Calling hook: configure_os
Extracting templates from packages: 100%
2012-09-12 11:37:36,745 INFO    : update-alternatives: error: no alternatives for rsh.
2012-09-12 11:37:36,821 INFO    : update-alternatives: error: no alternatives for rlogin.
2012-09-12 11:37:36,898 INFO    : update-alternatives: error: no alternatives for rcp.
2012-09-12 11:37:38,378 INFO    : Creating SSH2 RSA key; this may take some time ...
2012-09-12 11:37:38,589 INFO    : Creating SSH2 DSA key; this may take some time ...
2012-09-12 11:37:38,700 INFO    :
2012-09-12 11:37:38,700 INFO    : Warning: Fake initctl called, doing nothing
2012-09-12 11:37:38,701 INFO    :
2012-09-12 11:37:38,701 INFO    : Warning: Fake initctl called, doing nothing
2012-09-12 11:37:40,010 INFO    :
2012-09-12 11:37:40,011 INFO    : Current default time zone: 'Etc/UTC'
2012-09-12 11:37:40,014 INFO    : Local time is now:      Wed Sep 12 09:37:40 UTC 2012.
2012-09-12 11:37:40,014 INFO    : Universal Time is now:  Wed Sep 12 09:37:40 UTC 2012.
2012-09-12 11:37:40,014 INFO    :
Extracting templates from packages: 100%
2012-09-12 11:37:50,708 INFO    :
2012-09-12 11:37:50,709 INFO    : Current default time zone: 'Etc/UTC'
2012-09-12 11:37:50,711 INFO    : Local time is now:      Wed Sep 12 09:37:50 UTC 2012.
2012-09-12 11:37:50,714 INFO    : Universal Time is now:  Wed Sep 12 09:37:50 UTC 2012.
2012-09-12 11:37:50,714 INFO    : Run 'dpkg-reconfigure tzdata' if you wish to change it.
2012-09-12 11:37:50,714 INFO    :
2012-09-12 11:37:56,718 INFO    : Updating certificates in /etc/ssl/certs... WARNING: Skipping duplicate certificate ca-certificates.crt
2012-09-12 11:37:56,887 INFO    : 0 added, 1 removed; done.
2012-09-12 11:37:56,888 INFO    : Running hooks in /etc/ca-certificates/update.d....done.
2012-09-12 11:37:57,401 INFO    : start: Unknown parameter: JOB
2012-09-12 11:37:58,116 INFO    : restart: Unknown instance:
2012-09-12 11:37:59,146 INFO    : umount: /tmp/tmpC0GpKl/dev: device is busy.
2012-09-12 11:37:59,146 INFO    :         (In some cases useful info about processes that use
2012-09-12 11:37:59,146 INFO    :          the device is found by lsof(8) or fuser(1))
2012-09-12 11:37:59,147 INFO    : Cleaning up
2012-09-12 11:37:59,147 ERROR   : Process (['umount', '/tmp/tmpC0GpKl/dev']) returned 1. stdout: , stderr: umount: /tmp/tmpC0GpKl/dev: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))

Traceback (most recent call last):
  File "/usr/bin/vmbuilder", line 24, in <module>
    cli.main()
  File "/usr/lib/python2.7/dist-packages/VMBuilder/contrib/cli.py", line 216, in main
    distro.build_chroot()
  File "/usr/lib/python2.7/dist-packages/VMBuilder/distro.py", line 84, in build_chroot
    self.call_hooks('configure_os')
  File "/usr/lib/python2.7/dist-packages/VMBuilder/distro.py", line 67, in call_hooks
    call_hooks(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/util.py", line 165, in call_hooks
    getattr(context, func, log_no_such_method)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/distro.py", line 156, in configure_os
    self.suite.unmount_dev()
  File "/usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/dapper.py", line 118, in unmount_dev
    run_cmd('umount', '%s/dev' % self.context.chroot_dir)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/util.py", line 120, in run_cmd
    raise VMBuilderException, "Process (%s) returned %d. stdout: %s, stderr: %s" % (args.__repr__(), status, mystdout.buf, mystderr.buf)
VMBuilder.exception.VMBuilderException: Process (['umount', '/tmp/tmpC0GpKl/dev']) returned 1. stdout: , stderr: umount: /tmp/tmpC0GpKl/dev: device is busy.
        (In some cases useful info about processes that use
         the device is found by lsof(8) or fuser(1))

**Comment by devrandom** [comment]
Assuming this is not a current problem, please reopen if still an issue.
