### ISSUE TITLE
make-base-vm fails for 14.04/trusty

### ISSUE THREAD

**Issue by laanwj** [devrandom/gitian-builder#83]
I was trying this to experiment with a newer build environment. But it looks like it fails on the kernel.
```
Fetched 15.1 MB in 1s (7794 kB/s)
Selecting previously unselected package linux-image-3.13.0-46-generic.
(Reading database ... 24121 files and directories currently installed.)
Preparing to unpack .../linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb ...
Selecting previously unselected package linux-image-virtual.
Preparing to unpack .../linux-image-virtual_3.13.0.46.53_amd64.deb ...
Unpacking linux-image-virtual (3.13.0.46.53) ...
, stderr: grep: /proc/cpuinfo: No such file or directory
This kernel does not support a non-PAE CPU.
dpkg: error processing archive /var/cache/apt/archives/linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-46-generic /boot/vmlinuz-3.13.0-46-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-46-generic /boot/vmlinuz-3.13.0-46-generic
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

Traceback (most recent call last):
  File "/usr/bin/vmbuilder", line 24, in <module>
    cli.main()
  File "/usr/lib/python2.7/dist-packages/VMBuilder/contrib/cli.py", line 228, in main
    hypervisor.install_os()
  File "/usr/lib/python2.7/dist-packages/VMBuilder/hypervisor.py", line 70, in install_os
    self.call_hooks('install_kernel', self.chroot_dir)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/distro.py", line 67, in call_hooks
    call_hooks(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/util.py", line 159, in call_hooks
    getattr(plugin, func)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/distro.py", line 190, in install_kernel
    self.suite.install_kernel(destdir)
  File "/usr/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/dapper.py", line 307, in install_kernel
    run_cmd('chroot', destdir, 'apt-get', '--force-yes', '-y', 'install', self.kernel_name(), env={ 'DEBIAN_FRONTEND' : 'noninteractive' })
  File "/usr/lib/python2.7/dist-packages/VMBuilder/util.py", line 120, in run_cmd
    raise VMBuilderException, "Process (%s) returned %d. stdout: %s, stderr: %s" % (args.__repr__(), status, mystdout.buf, mystderr.buf)
VMBuilder.exception.VMBuilderException: Process (['chroot', '/tmp/tmpD1Hg3m', 'apt-get', '--force-yes', '-y', 'install', 'linux-image-virtual']) returned 100. stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  linux-image-3.13.0-46-generic
Suggested packages:
  fdutils linux-doc-3.13.0 linux-source-3.13.0 linux-tools
  linux-headers-3.13.0-46-generic
The following NEW packages will be installed:
  linux-image-3.13.0-46-generic linux-image-virtual
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 15.1 MB of archives.
After this operation, 42.2 MB of additional disk space will be used.
Get:1 http://127.0.0.1:3142/archive.ubuntu.com/ubuntu/ trusty-updates/main linux-image-3.13.0-46-generic amd64 3.13.0-46.79 [15.1 MB]
Get:2 http://127.0.0.1:3142/archive.ubuntu.com/ubuntu/ trusty-updates/main linux-image-virtual amd64 3.13.0.46.53 [2858 B]
Fetched 15.1 MB in 1s (7794 kB/s)
Selecting previously unselected package linux-image-3.13.0-46-generic.
(Reading database ... 24121 files and directories currently installed.)
Preparing to unpack .../linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb ...
Selecting previously unselected package linux-image-virtual.
Preparing to unpack .../linux-image-virtual_3.13.0.46.53_amd64.deb ...
Unpacking linux-image-virtual (3.13.0.46.53) ...
, stderr: grep: /proc/cpuinfo: No such file or directory
This kernel does not support a non-PAE CPU.
dpkg: error processing archive /var/cache/apt/archives/linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 3.13.0-46-generic /boot/vmlinuz-3.13.0-46-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 3.13.0-46-generic /boot/vmlinuz-3.13.0-46-generic
Errors were encountered while processing:
 /var/cache/apt/archives/linux-image-3.13.0-46-generic_3.13.0-46.79_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by devrandom** [comment]
Thank you for the report, looking...

**Comment by devrandom** [comment]
fixed in master: https://github.com/devrandom/gitian-builder/commit/b4201676d8e21d0b2e2e80f4889f01b0ed0e1913

**Comment by laanwj** [comment]
Thanks!
