### ISSUE TITLE
E: No such script: /usr/share/debootstrap/scripts/trusty

### ISSUE THREAD

**Issue by vertoe** [devrandom/gitian-builder#87]
I fail to create a base vm using the trusty suite.

```
vertoe@debian:~/gitian-builder$ sudo bin/make-base-vm --arch i386 --suite trusty
2015-05-06 13:26:23,216 INFO    : logging to file: /tmp/tmpTaXNB3
2015-05-06 13:26:23,444 INFO    : Calling hook: preflight_check
2015-05-06 13:26:23,456 INFO    : Calling hook: set_defaults
2015-05-06 13:26:23,457 INFO    : Calling hook: bootstrap
2015-05-06 13:26:23,730 INFO    : Cleaning up
2015-05-06 13:26:23,731 ERROR   : Process (['/usr/sbin/debootstrap', '--arch=i386', 'trusty', '/tmp/tmp5rw0Td', 'http://127.0.0.1:3142/archive.ubuntu.com/ubuntu']) returned 1. stdout: E: No such script: /usr/share/debootstrap/scripts/trusty
, stderr: 
Traceback (most recent call last):
  File "/usr/local/bin/vmbuilder", line 24, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/contrib/cli.py", line 221, in main
    distro.build_chroot()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/distro.py", line 83, in build_chroot
    self.call_hooks('bootstrap')
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/distro.py", line 67, in call_hooks
    call_hooks(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/util.py", line 170, in call_hooks
    getattr(context, func)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/distro.py", line 137, in bootstrap
    self.suite.debootstrap()
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/plugins/ubuntu/dapper.py", line 273, in debootstrap
    run_cmd(*cmd, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/VMBuilder/util.py", line 120, in run_cmd
    raise VMBuilderException, "Process (%s) returned %d. stdout: %s, stderr: %s" % (args.__repr__(), status, mystdout.buf, mystderr.buf)
VMBuilder.exception.VMBuilderException: Process (['/usr/sbin/debootstrap', '--arch=i386', 'trusty', '/tmp/tmp5rw0Td', 'http://127.0.0.1:3142/archive.ubuntu.com/ubuntu']) returned 1. stdout: E: No such script: /usr/share/debootstrap/scripts/trusty
, stderr:
```

Architecture doesnt matter, and it fails with the same error with or without LXC.

**Comment by josephbisch** [comment]
If you are using Debian Wheezy, then you either need to use the debootstrap package in wheezy-backports, or upgrade to Debian Jessie.

You can see that there is no trusty script in the normal Wheezy debootstrap package: https://packages.debian.org/wheezy/all/debootstrap/filelist.

**Comment by vertoe** [comment]
Ok, if it's host-related I can close this. Thanks for info.
